server:
  port: 80
  
example.property: "I am the production, hello"     

spring:
  datasource:
    url: jdbc:mysql://192.168.99.1:3306/licensing_service
    username: root
    password: root
   
  jpa:
    show-sql: true
    database: mysql
    
    
  jackson:
    serialization:
      indent-output: true  
    
    